export const LOBBY_STATES = {
  WAITING: 'Waiting For Players',
  STARTING: 'Starting Match',
  IN_MATCH: 'In Match',
  INTERMISSION: 'Between Rounds',
  ENDED: 'Match Ended',
  CLOSED: 'Closed'
};

const ability = (id, name, type, description, cooldown = 0, tags = [], extra = {}) => ({ id, name, type, description, cooldown, tags, ...extra });

export const MONSTER_ABILITY_POOL = [
  ability('sprint_burst', 'Sprint Burst', 'active', 'Short speed boost for a few seconds.', 16, ['speed'], { speed: 1.1 }),
  ability('lunge', 'Lunge', 'active', 'Quickly dash forward in the facing direction.', 18, ['lunge'], { range: 0.15 }),
  ability('echo_sense', 'Echo Sense', 'active', 'Briefly reveals survivor locations as glowing outlines through walls.', 32, ['sense', 'warning']),
  ability('door_slam', 'Door Slam', 'active', 'Closes nearby doors instantly.', 14, ['door']),
  ability('dark_pulse', 'Dark Pulse', 'active', 'Dims and flickers lights around the monster.', 24, ['blackout', 'warning']),
  ability('silent_steps', 'Silent Steps', 'active', 'Monster footsteps become quiet briefly.', 22, ['stealth']),
  ability('heartbeat_hunt', 'Heartbeat Hunt', 'passive', 'Heartbeat pressure and tracking cues are stronger near survivors.', 0, ['sense']),
  ability('fog_burst', 'Fog Burst', 'active', 'Creates a fog cloud in the current area.', 30, ['fog', 'warning']),
  ability('light_breaker', 'Light Breaker', 'active', 'Disables nearby room lights briefly.', 38, ['blackout']),
  ability('screech_stun', 'Screech Stun', 'active', 'Screech slows nearby survivors briefly.', 34, ['slow', 'warning']),
  ability('wall_crawl', 'Wall Crawl', 'active', 'Moves faster along walls for a short time.', 26, ['speed'], { speed: 0.45 }),
  ability('ceiling_cling', 'Ceiling Cling', 'active', 'Brief high-surface cling effect with tracking pressure.', 30, ['stealth']),
  ability('shadow_step', 'Shadow Step', 'active', 'Teleports a short distance while in darkness.', 36, ['teleport']),
  ability('door_phase', 'Door Phase', 'active', 'Passes through one closed door.', 28, ['door']),
  ability('heavy_charge', 'Heavy Charge', 'active', 'Rushes forward and forces doors open.', 34, ['lunge', 'door'], { range: 0.2 }),
  ability('long_arms', 'Long Arms', 'active', 'Attack range increases briefly.', 26, ['range'], { range: 0.85 }),
  ability('leap', 'Leap', 'active', 'Performs a forward leap.', 24, ['lunge']),
  ability('scent_trail', 'Scent Trail', 'passive', 'Sees fading survivor movement trails.', 0, ['sense']),
  ability('heat_vision', 'Heat Vision', 'active', 'Survivors glow faintly in dark rooms.', 35, ['sense', 'warning']),
  ability('puzzle_sense', 'Puzzle Sense', 'passive', 'Detects active puzzle station locations.', 0, ['sense']),
  ability('fear_pulse', 'Fear Pulse', 'active', 'Reveals nearby or stationary survivors.', 30, ['sense', 'warning']),
  ability('sound_marker', 'Sound Marker', 'passive', 'Loud survivor actions create pings.', 0, ['sense']),
  ability('footprint_glow', 'Footprint Glow', 'passive', 'Recent survivor footprints glow briefly.', 0, ['sense']),
  ability('last_seen', 'Last Seen', 'active', 'Shows ghost silhouettes at last known survivor positions.', 32, ['sense']),
  ability('breath_finder', 'Breath Finder', 'passive', 'Hears survivor breathing when close.', 0, ['sense']),
  ability('door_lock', 'Door Lock', 'active', 'Locks one nearby door temporarily.', 35, ['door', 'slow']),
  ability('trap_spawn', 'Trap Spawn', 'active', 'Places a slowing trap.', 45, ['trap', 'slow']),
  ability('hallway_stretch', 'Hallway Stretch', 'active', 'Distorts a hallway to confuse survivors.', 42, ['illusion', 'warning']),
  ability('room_blackout', 'Room Blackout', 'active', 'Turns off room lights temporarily.', 45, ['blackout', 'warning']),
  ability('false_puzzle_marker', 'False Puzzle Marker', 'active', 'Creates a fake glowing puzzle marker.', 32, ['illusion']),
  ability('quick_grab', 'Quick Grab', 'passive', 'Attack cooldown is slightly reduced.', 0, ['attack'], { cooldownBonus: 0.12 }),
  ability('claw_swipe', 'Claw Swipe', 'active', 'Wider short-range melee swipe.', 20, ['attack', 'range'], { range: 0.45 }),
  ability('chain_pull', 'Chain Pull', 'active', 'Pulls a nearby survivor slightly toward the monster.', 34, ['attack', 'slow']),
  ability('ground_pound', 'Ground Pound', 'active', 'Shockwave knocks nearby survivors back.', 38, ['attack', 'warning']),
  ability('venom_touch', 'Venom Touch', 'passive', 'Hit survivors are slowed briefly.', 0, ['attack', 'slow']),
  ability('bone_snap', 'Bone Snap', 'passive', 'Hit survivors lose sprint briefly.', 0, ['attack', 'slow']),
  ability('fear_bite', 'Fear Bite', 'passive', 'Hit survivors suffer darkened vision.', 0, ['attack', 'warning']),
  ability('pounce', 'Pounce', 'active', 'Jumps forward after a short windup.', 28, ['lunge']),
  ability('rage_strike', 'Rage Strike', 'passive', 'Missed attacks build slightly longer next range.', 0, ['attack'], { range: 0.2 }),
  ability('fake_footsteps', 'Fake Footsteps', 'active', 'Creates monster footstep sounds elsewhere.', 24, ['illusion']),
  ability('voice_mimic', 'Voice Mimic', 'active', 'Plays fake survivor sounds.', 28, ['illusion']),
  ability('clone_shadow', 'Clone Shadow', 'active', 'Creates a harmless moving shadow clone.', 40, ['illusion']),
  ability('invisible_flicker', 'Invisible Flicker', 'active', 'Monster becomes partially invisible briefly.', 48, ['stealth', 'warning']),
  ability('decoy_roar', 'Decoy Roar', 'active', 'Plays a roar from another location.', 26, ['illusion']),
  ability('false_puzzle_complete', 'False Puzzle Complete', 'active', 'Plays a fake puzzle complete cue.', 30, ['illusion']),
  ability('disguise_silhouette', 'Disguise Silhouette', 'active', 'Appears survivor-shaped from far away.', 50, ['illusion', 'stealth']),
  ability('mirror_image', 'Mirror Image', 'active', 'Creates fake images around the monster.', 42, ['illusion']),
  ability('fake_stun', 'Fake Stun', 'active', 'Appears stunned, then quickly recovers.', 36, ['illusion']),
  ability('static_mask', 'Static Mask', 'passive', 'Nearby survivor UI glitches.', 0, ['warning']),
  ability('puzzle_jam', 'Puzzle Jam', 'active', 'Slows progress on an active puzzle station.', 34, ['puzzle']),
  ability('puzzle_reset_tap', 'Puzzle Reset Tap', 'active', 'Reduces progress on one incomplete puzzle.', 40, ['puzzle']),
  ability('code_scramble', 'Code Scramble', 'active', 'Scrambles future code puzzle state.', 36, ['puzzle']),
  ability('battery_drain', 'Battery Drain', 'active', 'Drains future battery item progress.', 34, ['puzzle']),
  ability('radio_static', 'Radio Static', 'active', 'Adds loud static near survivors.', 26, ['warning']),
  ability('pressure_spike', 'Pressure Spike', 'active', 'Puzzle progress briefly shakes or pauses.', 34, ['puzzle', 'warning']),
  ability('wire_spark', 'Wire Spark', 'active', 'Creates a shock near an active puzzle station.', 28, ['puzzle']),
  ability('mirror_shake', 'Mirror Shake', 'active', 'Shakes future mirror puzzle alignment.', 30, ['puzzle']),
  ability('core_instability', 'Core Instability', 'active', 'Later rounds slow puzzle progress briefly.', 45, ['puzzle']),
  ability('tunnel_vision', 'Tunnel Vision', 'active', 'Narrows nearby survivor vision briefly.', 38, ['warning']),
  ability('flash_horror', 'Flash Horror', 'active', 'Quick monster flash for nearby survivors.', 32, ['warning']),
  ability('whisper_cloud', 'Whisper Cloud', 'active', 'Whispers and fake directional sounds.', 30, ['warning', 'illusion']),
  ability('panic_pulse', 'Panic Pulse', 'active', 'Survivor hands shake slightly.', 34, ['warning']),
  ability('static_vision', 'Static Vision', 'active', 'Adds visual static to nearby survivors.', 38, ['warning']),
  ability('reverse_sound', 'Reverse Sound', 'active', 'Monster sounds seem to come from wrong directions.', 30, ['illusion']),
  ability('breath_fog', 'Breath Fog', 'passive', 'Survivor vision gets foggy when monster is near.', 0, ['warning']),
  ability('flicker_world', 'Flicker World', 'active', 'Lights rapidly flicker around survivors.', 36, ['blackout', 'warning']),
  ability('false_heartbeat', 'False Heartbeat', 'active', 'Survivors hear fake heartbeat sounds.', 30, ['illusion', 'warning']),
  ability('fear_meter_spike', 'Fear Meter Spike', 'active', 'Creates screen shake and fear audio.', 34, ['warning']),
  ability('armor_hide', 'Armor Hide', 'passive', 'More resistant to future stuns and slows.', 0, ['resist']),
  ability('trap_immunity', 'Trap Immunity', 'passive', 'Ignores future trap effects.', 0, ['resist']),
  ability('light_resistance', 'Light Resistance', 'passive', 'Bright light effects affect monster less.', 0, ['resist']),
  ability('stun_recovery', 'Stun Recovery', 'passive', 'Recovers faster from future stuns.', 0, ['resist']),
  ability('door_breaker', 'Door Breaker', 'passive', 'Opens and breaks doors faster.', 0, ['door', 'speed'], { speed: 0.15 }),
  ability('puzzle_guardian', 'Puzzle Guardian', 'passive', 'Moves faster near active puzzles.', 0, ['speed', 'puzzle'], { speed: 0.2 }),
  ability('rage_build', 'Rage Build', 'passive', 'Slowly gains speed if survivors avoid it too long.', 0, ['speed'], { speed: 0.18 }),
  ability('anti_still_sense', 'Anti-Still Sense', 'passive', 'Detects survivors who stand still too long.', 0, ['sense']),
  ability('noise_shield', 'Noise Shield', 'passive', 'Monster ability sounds are quieter.', 0, ['stealth']),
  ability('hunt_focus', 'Hunt Focus', 'passive', 'Cooldowns shorten when one survivor remains.', 0, ['cooldown'], { cooldownBonus: 0.15 }),
  ability('split_body', 'Split Body', 'active', 'Creates a shadow clone running forward.', 42, ['illusion']),
  ability('time_skip', 'Time Skip', 'active', 'Teleports a short distance forward.', 45, ['teleport']),
  ability('gravity_drag', 'Gravity Drag', 'active', 'Survivors in same room move slower briefly.', 42, ['slow', 'warning']),
  ability('blood_mark', 'Blood Mark', 'active', 'Marks one survivor for temporary tracking.', 48, ['sense', 'warning']),
  ability('room_curse', 'Room Curse', 'active', 'Marks one room with fog and slowing pressure.', 55, ['fog', 'slow', 'warning']),
  ability('hunt_bell', 'Hunt Bell', 'active', 'Loud survivor movement creates pings.', 36, ['sense']),
  ability('light_eater', 'Light Eater', 'passive', 'Moves faster in dark areas.', 0, ['speed'], { speed: 0.2 }),
  ability('panic_swap', 'Panic Swap', 'active', 'Swaps two active puzzle station markers.', 50, ['puzzle', 'illusion']),
  ability('shadow_hand', 'Shadow Hand', 'active', 'Sends a short-range shadow grab forward.', 32, ['attack', 'range'], { range: 0.55 }),
  ability('blackout_hunt', 'Blackout Hunt', 'passive', 'Gains speed during blackout effects.', 0, ['speed', 'blackout'], { speed: 0.22 }),
  ability('bigger_body', 'Bigger Body', 'passive', 'Monster grows larger, louder, and more imposing.', 0, ['range'], { range: 0.25 }),
  ability('extra_arm', 'Extra Arm', 'passive', 'Slightly wider attack angle.', 0, ['attack', 'range'], { range: 0.25 }),
  ability('spider_form', 'Spider Form', 'active', 'Temporarily crawls faster with creepier movement.', 36, ['speed'], { speed: 0.75 }),
  ability('split_jaw', 'Split Jaw', 'passive', 'Screech effects have larger range.', 0, ['warning']),
  ability('lantern_eyes', 'Lantern Eyes', 'active', 'Glowing eyes reveal nearby survivors.', 35, ['sense']),
  ability('thorn_skin', 'Thorn Skin', 'passive', 'Survivors touching the monster are slowed.', 0, ['slow']),
  ability('smoke_body', 'Smoke Body', 'active', 'Leaves a smoke trail that blocks vision.', 42, ['fog']),
  ability('bone_wings', 'Bone Wings', 'active', 'Glides or leaps farther.', 38, ['lunge']),
  ability('final_form', 'Final Form', 'passive', 'Round 10 cooldowns are reduced.', 0, ['cooldown'], { cooldownBonus: 0.12 }),
  ability('doom_sense', 'Doom Sense', 'passive', 'Round 10 periodically senses nearest survivor.', 0, ['sense']),
  ability('rule_breaker', 'Rule Breaker', 'active', 'Once per match, activates two owned abilities together.', 90, ['once', 'cooldown']),
  ability('last_hunt', 'Last Hunt', 'passive', 'When one survivor remains, gains speed and tracking.', 0, ['speed', 'sense'], { speed: 0.45 })
];

const makePuzzle = (id, name, verb, prompt, objects = []) => ({ id, name, verb, prompt, objects });

export const PUZZLE_TYPES = [
  makePuzzle('switch_sequence', 'Switch Sequence', 'Flip', 'Hold E to flip the switches in the clue order. Wrong order resets the panel.', ['switches', 'clue plaque']),
  makePuzzle('keycard_scanner', 'Keycard Scanner', 'Insert', 'Hold E to grab the nearby keycard, carry it to the scanner, and insert it.', ['keycard', 'scanner']),
  makePuzzle('valve_pressure', 'Valve Pressure', 'Turn', 'Hold E to turn valve wheels until the pressure needle stays in the green zone.', ['valves', 'pressure meter']),
  makePuzzle('wire_match', 'Wire Match', 'Connect', 'Hold E to connect loose colored wires to matching sockets.', ['colored wires', 'sockets']),
  makePuzzle('hidden_code', 'Hidden Code', 'Enter', 'Hold E to enter the code hidden on a nearby note, wall, screen, or object.', ['keypad', 'hidden note']),
  makePuzzle('battery_delivery', 'Battery Delivery', 'Power', 'Hold E to collect a battery, insert it into the generator, then press power.', ['battery', 'generator']),
  makePuzzle('mirror_beam', 'Mirror Beam', 'Rotate', 'Hold E to rotate mirrors until the light beam hits the receiver.', ['mirrors', 'beam receiver']),
  makePuzzle('fuse_box', 'Fuse Box', 'Place', 'Hold E to find missing fuses and place them into the fuse box.', ['fuses', 'fuse box']),
  makePuzzle('dual_button', 'Dual Button', 'Press', 'Hold E to synchronize two buttons. Solo survivors use a heavy object on one button.', ['dual buttons', 'heavy object']),
  makePuzzle('radio_repair', 'Radio Repair', 'Repair', 'Hold E to install antenna, knob, and power cell, then turn on the radio.', ['antenna', 'knob', 'power cell']),
  makePuzzle('pipe_rotation', 'Pipe Rotation', 'Rotate', 'Hold E to rotate pipe pieces until the path connects from start to end.', ['pipe grid']),
  makePuzzle('symbol_match', 'Symbol Match', 'Match', 'Hold E to press symbol buttons in the exact wall sequence.', ['symbols', 'buttons']),
  makePuzzle('crank_door', 'Crank Door', 'Crank', 'Hold E to crank repeatedly until the unlock meter fills.', ['crank', 'unlock meter']),
  makePuzzle('broken_elevator', 'Broken Elevator', 'Restore', 'Hold E to insert wires, lever, and fuse, then pull the elevator lever.', ['wires', 'lever', 'fuse']),
  makePuzzle('candle_pattern', 'Candle Pattern', 'Light', 'Hold E to light candles in the clue order. Wrong order blows them out.', ['candles', 'ritual clue']),
  makePuzzle('safe_dial', 'Safe Dial', 'Dial', 'Hold E to rotate the safe dial to the nearby combination.', ['safe', 'combination clue']),
  makePuzzle('water_pump', 'Water Pump', 'Pump', 'Hold E to pump the handle until the water pressure meter fills.', ['pump handle', 'water meter']),
  makePuzzle('gear_machine', 'Gear Machine', 'Install', 'Hold E to place missing gears into matching slots and activate the machine.', ['gears', 'gear slots']),
  makePuzzle('book_puzzle', 'Book Puzzle', 'Sort', 'Hold E to place books on the shelf in number, color, or symbol order.', ['books', 'shelf']),
  makePuzzle('security_camera_reset', 'Security Camera Reset', 'Reset', 'Hold E to reset every active camera node.', ['camera nodes']),
  makePuzzle('bell_rhythm', 'Bell Rhythm', 'Ring', 'Hold E to ring bells in the rhythm shown by flashing lights or audio beats.', ['bells', 'rhythm lights']),
  makePuzzle('object_weighing', 'Object Weighing', 'Balance', 'Hold E to place objects on the scale until it balances in the green zone.', ['scale', 'weights']),
  makePuzzle('fuse_color_logic', 'Fuse Color Logic', 'Solve', 'Hold E to insert colored fuses into clue-matched symbol slots.', ['colored fuses', 'symbol slots']),
  makePuzzle('lever_timing', 'Lever Timing', 'Time', 'Hold E to pull levers only when the nearby light flashes green.', ['levers', 'green timing light']),
  makePuzzle('locked_chest', 'Locked Chest', 'Unlock', 'Hold E to find three keys and unlock every chest lock.', ['three keys', 'locked chest']),
  makePuzzle('sound_puzzle', 'Sound Puzzle', 'Listen', 'Hold E to match the machine sound with the correct room object.', ['sound machine', 'matching object']),
  makePuzzle('heat_vent', 'Heat Vent Puzzle', 'Close', 'Hold E to close overheating vents before the heat meter fills.', ['vents', 'heat meter']),
  makePuzzle('maze_panel', 'Maze Panel', 'Guide', 'Hold E to guide the ball through the panel maze to the end.', ['maze panel', 'ball']),
  makePuzzle('laser_redirect', 'Laser Redirect', 'Redirect', 'Hold E to rotate prisms and redirect lasers into matching receivers.', ['prisms', 'laser receivers']),
  makePuzzle('light_pattern_memory', 'Light Pattern Memory', 'Repeat', 'Hold E to repeat the flashed light pattern on the buttons.', ['memory lights', 'buttons']),
  makePuzzle('broken_clock', 'Broken Clock', 'Set', 'Hold E to set the clock hands to the clue time.', ['clock', 'time clue']),
  makePuzzle('chemical_mix', 'Chemical Mix', 'Mix', 'Hold E to pour colored liquids into the machine in the correct order.', ['liquids', 'mixer']),
  makePuzzle('statue_rotation', 'Statue Rotation', 'Rotate', 'Hold E to rotate statues toward the correct symbols or directions.', ['statues', 'direction symbols']),
  makePuzzle('generator_restart', 'Generator Restart', 'Restart', 'Hold E to pull the starter cord, flip a switch, and hold the ignition button.', ['starter cord', 'switch', 'button']),
  makePuzzle('archive_search', 'Archive Search', 'Search', 'Hold E to search files and drawers for the correct ID number.', ['files', 'drawers']),
  makePuzzle('lock_combination', 'Lock Combination', 'Unlock', 'Hold E to enter the clue combination into the padlock.', ['padlock', 'combination clue']),
  makePuzzle('circuit_board', 'Circuit Board', 'Install', 'Hold E to place chips into matching shaped circuit slots.', ['chips', 'circuit board']),
  makePuzzle('power_reroute', 'Power Reroute', 'Reroute', 'Hold E to redirect power through switches along the glowing path.', ['power switches', 'glowing line']),
  makePuzzle('morse_code_panel', 'Morse Code Panel', 'Copy', 'Hold E to copy short and long beep patterns with the input button.', ['morse speaker', 'input button']),
  makePuzzle('hidden_object_hunt', 'Hidden Object Hunt', 'Find', 'Hold E to find three marked objects and place them on the table.', ['marked objects', 'table']),
  makePuzzle('door_symbol_chain', 'Door Symbol Chain', 'Chain', 'Hold E to press locked-door symbols in the nearby chain order.', ['door symbols', 'chain clue']),
  makePuzzle('emergency_override', 'Emergency Override', 'Override', 'Hold E to run the override. Solo survivors get a timed single-player sequence.', ['override button', 'lever']),
  makePuzzle('broken_robot', 'Broken Robot', 'Repair', 'Hold E to reattach the robot head, arm, and battery.', ['robot head', 'arm', 'battery']),
  makePuzzle('pressure_plate_path', 'Pressure Plate Path', 'Step', 'Hold E to activate floor plates in the correct path order.', ['floor plates']),
  makePuzzle('vent_fan_shutdown', 'Vent Fan Shutdown', 'Stop', 'Hold E to press fan controls until spinning vents stop.', ['fan controls', 'vents']),
  makePuzzle('crystal_alignment', 'Crystal Alignment', 'Align', 'Hold E to rotate crystals until their glows connect.', ['crystals', 'glow links']),
  makePuzzle('computer_terminal', 'Computer Terminal', 'Command', 'Hold E to select the correct terminal command sequence.', ['terminal']),
  makePuzzle('magnet_puzzle', 'Magnet Puzzle', 'Magnetize', 'Hold E to use the magnet tool to move the metal ball into the goal.', ['magnet tool', 'metal ball']),
  makePuzzle('security_badge', 'Security Badge Puzzle', 'Match', 'Hold E to match badges to stations by name, color, or symbol.', ['badges', 'stations']),
  makePuzzle('final_round_core', 'Final Round Core', 'Stabilize', 'Hold E to insert cells, turn valves, press buttons, and stabilize the glowing core.', ['power cells', 'valves', 'buttons', 'core'])
];

export const TUNING = {
  survivorSpeed: 5.25,
  monsterBaseSpeed: 4.85,
  puzzleHoldSeconds: 2.4,
  attackCooldown: 1.15,
  attackRangeBase: 1.65,
  roundCount: 10,
  playerRadius: 0.45,
  minPlayers: 2,
  maxPlayers: 4,
  minPuzzlesPerRound: 5,
  maxPuzzlesPerRound: 10
};
